environment:
  matrix:
  - TARGET: python27
    PYTHON: "C:\\Python27"
  - TARGET: python36
    PYTHON: "C:\\Python36"

matrix:
  allow_failures:
  - TARGET: python36

install:
- cmd: '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86 /release'
- cmd: "%PYTHON%\\python.exe -m pip install --upgrade pip"
- cmd: "%PYTHON%\\Scripts\\pip.exe install pywin32 WMI"
- cmd: "%PYTHON%\\python.exe %PYTHON%\\Scripts\\pywin32_postinstall.py -install"

build: off

test_script:
- "%PYTHON%\\python.exe run_tests.py"
